FROM osrf/ros:melodic-desktop-full

SHELL ["/bin/bash", "-c"]

env:
  cache-version: v0.0.1

ENV ROS_MASTER_URI=http://localhost:11311 \
  ROS_HOSTNAME=localhost

RUN apt update && apt upgrade -y && \ 
  apt install -y \
  xvfb \
  ffmpeg \
  psmisc \
  python3-pip \
  # Install ros related
  python-catkin-tools && \
  pip3 install rospkg catkin_pkg