odom_frame_id: odom
base_frame_id: base_footprint

min_particles: 500
max_particles: 3000
kld_err: 0.02
kld_z: 0.95
update_min_d: 0.20
update_min_a: 0.20
resample_interval: 1
transform_tolerance: 0.5
recovery_alpha_slow: 0.00
recovery_alpha_fast: 0.00

laser_max_beams: 180
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2
laser_model_type: likelihood_field

odom_model_type: diff #r is rotation, t is translation
odom_alpha1: 0.2  #rr
odom_alpha2: 0.9  #tr
odom_alpha3: 2.0  #tt
odom_alpha4: 0.3  #rt

gui_publish_rate: 50.0