DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.4
  min_vel_x: 0

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans: 0.3
  min_vel_trans: 0.1
  
  max_vel_theta: 1.0
  min_vel_theta: 0.4

  acc_lim_x: 10
  acc_lim_y: 0.0
  acc_lim_theta: 10

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 20
  vy_samples: 0
  vth_samples: 30

# Trajectory Scoring Parameters
  path_distance_bias: 0.4
  goal_distance_bias: 0.3
  occdist_scale: 0.0004
  twirling_scale: 0.0
  forward_point_distance: 0.3
  stop_time_buffer: 0.2
  scaling_speed: 1.0
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  oscillation_rest_angle: 0.2

  # Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: false
  prune_plan: true