global_frame: map
robot_base_frame: base_link

footprint: [[-0.37, -0.25], [-0.37, 0.25], [0.2, 0.25], [0.2, -0.25]]
inflation_radius: 1.0
cost_scaling_factor: 10

update_frequency: 5
publish_frequency: 5
transform_tolerance: 2

rolling_window: false
always_send_full_costmap: true

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer" }
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer" }