waypoint_nav:
  controller_frequency: 10
  num_callback_threads: 1
  waypoint_area_rdias: 3

  loop_navigation: true
  speed_variable: true
  cmd_vel_smoother: true
  waypoint_area_rdias_variable: true
  for_move_base_map: true
  goal_send_loop: true
  
  base_link_frame: base_link
  base_foot_print_frame: base_link
  odom_frame: odom

  waypoint_helper_plugins:
    - {name: hogehoge, type: hoge}
    - {name: hogehoge, type: hoge}