odom_freq                     : 15
num_particles                 : 500
odom_frame_id                 : odom
footprint_frame_id            : base_footprint
base_frame_id                 : base_link
odom_fw_dev_per_fw            : 0.5
odom_fw_dev_per_rot           : 0.2
odom_rot_dev_per_fw           : 0.13
odom_rot_dev_per_rot          : 0.05
laser_likelihood_max_dist     : 2.0
alpha_threshold               : 0.3
open_space_threshold          : 0.05
expansion_radius_position     : 0.1
expansion_radius_orientation  : 0.2
range_threshold               : 0.3
laser_min_range               : 0.0
laser_max_range               : 60.0
scan_increment                : 3