waypoints:
  - id: 1
    position:
      x: 7.749710
      y: -0.362790
    euler_angle:
      z: -0.0638248225954985
    properties:
      - function: variable_speed
        vel_trans: 0.3
  - id: 2
    position:
      x: 19.975597
      y: -0.901446
    euler_angle:
      z: 1.502107171059494
    properties:
      - function: attention_speak
      - function: variable_waypoint_radius
        waypoint_radius: 1.0
  - id: 3
    position:
      x: 14.3
      y: 9.123
    euler_angle:
      z: 3.098
    properties:
      - function: attention_speak
      - function: variable_waypoint_radius
        waypoint_radius: 2.0
  - id: 4
    position:
      x: -13.854096
      y: 9.386736
    euler_angle:
      z: -1.603556631084992
    properties:
      - function: stop
      - function: variable_speed
        vel_trans: 0.8
  - id: 5
    position:
      x: -14.292275
      y: 0.630507
    euler_angle:
      z: -0.05675763783324143
  - id: 6
    position:
      x: 0.051527
      y: 0.022442
    euler_angle:
      z: -0.07325240125722614
    properties:
      - function: goal
      - function: loop
