name: ros1-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD
        if: ${{ github.event == 'pull_request' }}
        run: |
          echo "a"      
        if: ${{ github.event == 'push' }}
        run: |
          echo "b"