name: ros1-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD PUSH
        if: ${{ github.event_name == 'push' }}
        run: |
          docker build --no-cache -t ubeike/raspicat-ros1-melodic-navigation -f ./.github/Dockerfile.ci ./.github
      - name: BUILD PULL REQUEST
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sed -i -e "s;false;true;" ./.github/Dockerfile.ci
          sed -i -e "s;pull/ID/head;"$(echo "${GITHUB_REF#refs/heads/}" | sed -e "s;refs/;;")";" ./.github/Dockerfile.ci
          docker build --no-cache -t ubeike/raspicat-ros1-melodic-navigation -f ./.github/Dockerfile.ci ./.github
          