name: ros1-melodic-ci

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD
        run: |
          docker build --no-cache -t ubeike/raspicat-ros1-melodic-navigation -f ./.github/Dockerfile.ci ./.github
      - name: TEST
        run: |
          docker run --init ubeike/raspicat-ros1-melodic-navigation ./test/ci_test.sh