name: ros-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  Build-and-Test:
    runs-on: ubuntu-18.04

    steps:
      - name: Run actions/checkout@v2 
        uses: actions/checkout@v2
      - name: Build push
        if: ${{ github.event_name == 'push' }}
        run: |
          docker build --no-cache -t ubeike/raspicat-ros-melodic-navigation -f ./.github/Dockerfile.ci ./.github
      - name: Build pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sed -i -e "s;false;true;" ./.github/Dockerfile.ci
          sed -i -e "s;pull/ID/head;"$(echo "${GITHUB_REF#refs/heads/}" | sed -e "s;refs/;;")";" ./.github/Dockerfile.ci
          docker build --no-cache -t ubeike/raspicat-ros-melodic-navigation -f ./.github/Dockerfile.ci ./.github
      - name: Test
        run: |
          docker run --init ubeike/raspicat-ros-melodic-navigation /bin/bash -c "source /home/.bashrc && ./test/ci_test.sh"
          