name: ros1-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD_PUSH
        run: |
          echo "${{ github.event_name }}"
      - name: BUILD_PR
        run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.ref }}"