name: ros1-melodic-ci

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD
        run: |
          ./.github/environment_ci.sh
          docker ps -a
      - name: TEST
        run: |
          docker ps -a
          ./test/ci_test.sh