name: ros1-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  OS-Set:
    runs-on: ubuntu-18.04

  checkout@v2:
    - uses: actions/checkout@v2
    - name: BUILD

  build:
    if: ${{ github.event == 'pull_request' }}
    steps:
      run: |
        echo "a"      
    if: ${{ github.event == 'push' }}
    steps:
      run: |
        echo "b"