name: ros-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

env:
  DOCKER-IMAGE: ubeike/raspicat-navigation-ros-melodic-ci
  DOCKER-CONTEXT: ./
  DOCKER-FILE-ENVIRONMENT: ./.github/Dockerfile.environment-ci
  DOCKER-FILE-BUILD: ./.github/Dockerfile.build-ci

jobs:
  Build:
    runs-on: ubuntu-18.04

    steps:
      - name: Run actions/checkout@v2 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      
      - name: Create environment docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-ENVIRONMENT }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.DOCKER-IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Sed clone url
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sed -i -e "s;false;true;" ./.github/Dockerfile.build-ci
          sed -i -e "s;pull/ID/head;"$(echo "${GITHUB_REF#refs/heads/}" | sed -e "s;refs/;;")";" ./.github/Dockerfile.build-ci

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE-BUILD }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER-IMAGE }}

  Test:
    runs-on: ubuntu-18.04

    needs: Build
    steps:
      - name: Test
        run: |
          docker run --init ubeike/raspicat-navigation-ros-melodic-ci /bin/bash -c "source /root/.bashrc && ./test/ci_test.sh"