name: ros1-melodic-ci

on:
  push:
    branches:
      - master
    paths-ignore:
    - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: BUILD
        run: |
          sed -i -e "s/branch-arg/"${GITHUB_REF#refs/heads/}"/g" ./.github/Dockerfile.ci
          docker build --no-cache -t ubeike/raspicat-ros1-melodic-navigation -f ./.github/Dockerfile.ci ./.github
      - name: TEST
        run: |
          docker run --init ubeike/raspicat-ros1-melodic-navigation /bin/bash -c "source /home/.bashrc && ./test/ci_test.sh"